GET http://localhost:3000/register

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Bruce",
    "password": "asd"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"Bruce",
    "password": "asd"
}

